//
//  CarBrandData.swift
//  RizQPay
//
//  Created by Nursultan Yelemessov on 03/11/2025.
//

import Foundation

// MARK: - Car Data Structure
struct CarBrandData {
    static let carBrandModels: [String: [String]] = [
        
        "Acura": ["CL",
                  "EL",
                  "ILX",
                  "Integra",
                  "Legend",
                  "MDX",
                  "NSX",
                  "RDX",
                  "RL",
                  "RLX",
                  "RSX",
                  "SLX",
                  "TL",
                  "TLX",
                  "TSX",
                  "Vigor",
                  "ZDX"],
        
        "Alfa Romeo": ["145",
                       "146",
                       "147",
                       "155",
                       "156",
                       "159",
                       "164",
                       "166",
                       "33",
                       "4C",
                       "75",
                       "90",
                       "Alfa 6",
                       "Arna",
                       "Brera",
                       "Giulia",
                       "Giulietta",
                       "GT",
                       "GTV",
                       "MiTo",
                       "Spider",
                       "Stelvio",
                       "Tonale"],
        
        "Aston Martin": ["Cygnet",
                         "DB7",
                         "DB9",
                         "DB11",
                         "DBS",
                         "DBX",
                         "Lagonda",
                         "One-77",
                         "Rapide",
                         "V12 Vantage",
                         "V8 Vantage",
                         "Vanquish",
                         "Vantage",
                         "Virage"],
        
        "Audi": ["100",
                 "200",
                 "80",
                 "90",
                 "A1",
                 "A3",
                 "A4",
                 "A4 Allroad",
                 "A5",
                 "A6",
                 "A6 Allroad",
                 "A7",
                 "A8",
                 "E-Tron",
                 "E-Tron GT",
                 "Q2",
                 "Q3",
                 "Q4 E-Tron",
                 "Q5",
                 "Q7",
                 "Q8",
                 "R8",
                 "RS3",
                 "RS4",
                 "RS5",
                 "RS6",
                 "RS7",
                 "RS Q8",
                 "S1",
                 "S3",
                 "S4",
                 "S5",
                 "S6",
                 "S7",
                 "S8",
                 "SQ2",
                 "SQ5",
                 "SQ7",
                 "SQ8",
                 "TT",
                 "TT RS",
                 "TTS"],
        
        "Avatr": ["11",
                  "12"],
        
        "Baic": ["Arcfox αS",
                 "Arcfox αT",
                 "BJ30",
                 "BJ40",
                 "BJ60",
                 "BJ80",
                 "EU5",
                 "EU7",
                 "X3",
                 "X5",
                 "X7"],
        
        "BMW": ["1 Series",
                "2 Series",
                "3 Series",
                "4 Series",
                "5 Series",
                "6 Series",
                "7 Series",
                "8 Series",
                "i3",
                "i4",
                "i8",
                "iX",
                "iX3",
                "M1",
                "M2",
                "M3",
                "M4",
                "M5",
                "M6",
                "M8",
                "X1",
                "X2",
                "X3",
                "X4",
                "X5",
                "X6",
                "X7",
                "XM",
                "Z1",
                "Z3",
                "Z4",
                "Z8"],
        
        "Buick": ["Cascada",
                  "Century",
                  "Enclave",
                  "Encore",
                  "Envision",
                  "Envista",
                  "LaCrosse",
                  "LeSabre",
                  "Lucerne",
                  "Park Avenue",
                  "Rainier",
                  "Regal",
                  "Rendezvous",
                  "Riviera",
                  "Roadmaster",
                  "Skylark",
                  "Terraza",
                  "Verano"],
        
        "BYD": ["Atto 3",
                "Dolphin",
                "E6",
                "F0",
                "F3",
                "F6",
                "G3",
                "G6",
                "Han",
                "L3",
                "M6",
                "S6",
                "S7",
                "Seal",
                "Song",
                "Tang",
                "Yuan"],
        
        "Cadillac": ["ATS",
                     "CTS",
                     "CT4",
                     "CT5",
                     "CT6",
                     "DeVille",
                     "DTS",
                     "Eldorado",
                     "Escalade",
                     "Fleetwood",
                     "Lyriq",
                     "Seville",
                     "SRX",
                     "STS",
                     "XT4",
                     "XT5",
                     "XT6",
                     "XTS"],
        
        "Changan": ["Alsvin",
                    "BenBen",
                    "CS15",
                    "CS35",
                    "CS55",
                    "CS75",
                    "CS85",
                    "CS95",
                    "Eado",
                    "Hunter",
                    "Raeton",
                    "UNI-K",
                    "UNI-T",
                    "UNI-V"],
        
        "Chery": ["Arrizo 3",
                  "Arrizo 5",
                  "Arrizo 6",
                  "Arrizo 7",
                  "Arrizo 8",
                  "QQ",
                  "Tiggo 2",
                  "Tiggo 3",
                  "Tiggo 4",
                  "Tiggo 5",
                  "Tiggo 7",
                  "Tiggo 8"],
        
        "Chevrolet": ["Aveo",
                      "Blazer",
                      "Bolt",
                      "Camaro",
                      "Captiva",
                      "Cobalt",
                      "Colorado",
                      "Corvette",
                      "Cruze",
                      "Equinox",
                      "Express",
                      "HHR",
                      "Impala",
                      "Kalos",
                      "Lacetti",
                      "Malibu",
                      "Matiz",
                      "Monte Carlo",
                      "Orlando",
                      "Silverado",
                      "Sonic",
                      "Spark",
                      "Suburban",
                      "Tahoe",
                      "Tracker",
                      "Trailblazer",
                      "Traverse",
                      "Volt"],
        
        "Chrysler": ["200",
                     "300",
                     "300C",
                     "300M",
                     "Aspen",
                     "Concorde",
                     "Crossfire",
                     "Grand Voyager",
                     "LHS",
                     "Neon",
                     "Pacifica",
                     "PT Cruiser",
                     "Sebring",
                     "Town & Country",
                     "Voyager"],
        
        "Citroen": ["Berlingo",
                    "C1",
                    "C2",
                    "C3",
                    "C3 Aircross",
                    "C4",
                    "C4 Cactus",
                    "C4 Picasso",
                    "C5",
                    "C5 Aircross",
                    "C6",
                    "C8",
                    "DS3",
                    "DS4",
                    "DS5",
                    "Jumper",
                    "Jumpy",
                    "Nemo",
                    "Saxo",
                    "SpaceTourer",
                    "Xantia",
                    "XM",
                    "Xsara"],
        
        "Dodge": ["Avenger",
                  "Caliber",
                  "Challenger",
                  "Charger",
                  "Dakota",
                  "Dart",
                  "Durango",
                  "Grand Caravan",
                  "Journey",
                  "Magnum",
                  "Nitro",
                  "Ram",
                  "Stratus",
                  "Viper"],
        
        "Exeed": ["LX",
                  "RX",
                  "TX",
                  "TXL",
                  "VX"],
        
        "Ferrari": ["296",
                    "308",
                    "328",
                    "348",
                    "360",
                    "458",
                    "488",
                    "812",
                    "California",
                    "Daytona",
                    "Enzo",
                    "F40",
                    "F50",
                    "F8",
                    "F12",
                    "FF",
                    "GTC4Lusso",
                    "LaFerrari",
                    "Mondial",
                    "Portofino",
                    "Purosangue",
                    "Roma",
                    "SF90",
                    "Testarossa"],
        
        "Fiat": ["124",
                 "500",
                 "500L",
                 "500X",
                 "Albea",
                 "Barchetta",
                 "Bravo",
                 "Croma",
                 "Doblo",
                 "Ducato",
                 "Fiorino",
                 "Linea",
                 "Multipla",
                 "Panda",
                 "Punto",
                 "Qubo",
                 "Stilo",
                 "Tipo",
                 "Uno"],
        
        "Ford": ["Aerostar",
                 "B-Max",
                 "Bronco",
                 "C-Max",
                 "Contour",
                 "Crown Victoria",
                 "EcoSport",
                 "Edge",
                 "Escape",
                 "Escort",
                 "Expedition",
                 "Explorer",
                 "F-150",
                 "F-250",
                 "F-350",
                 "Fiesta",
                 "Five Hundred",
                 "Flex",
                 "Focus",
                 "Freestar",
                 "Freestyle",
                 "Fusion",
                 "Galaxy",
                 "Ka",
                 "Kuga",
                 "Mondeo",
                 "Mustang",
                 "Puma",
                 "Ranger",
                 "S-Max",
                 "Taurus",
                 "Territory",
                 "Thunderbird",
                 "Transit",
                 "Windstar"],
        
        "Forthing": ["S50",
                     "T5",
                     "T5 EVO",
                     "T5L",
                     "U-Tour",
                     "Yacht"],
        
        "Gac": ["Aion LX",
                "Aion S",
                "Aion V",
                "Aion Y",
                "Emkoo",
                "Empow",
                "Emzoom",
                "GA4",
                "GA6",
                "GA8",
                "GS3",
                "GS4",
                "GS5",
                "GS8"],
        
        "Geely": ["Atlas",
                  "Boyue",
                  "Binyue",
                  "Coolray",
                  "Emgrand 7",
                  "Emgrand X7",
                  "Geometry A",
                  "Geometry C",
                  "Monjaro",
                  "Okavango",
                  "Tugella",
                  "Vision"],
        
        "Genesis": ["G70",
                    "G80",
                    "G90",
                    "GV60",
                    "GV70",
                    "GV80"],
        
        "GMC": ["Acadia",
                "Canyon",
                "Envoy",
                "Hummer EV",
                "Jimmy",
                "Savana",
                "Sierra",
                "Sonoma",
                "Terrain",
                "Yukon"],
        
        "GWM": ["Poer",
                "Tank 300",
                "Tank 500",
                "Wingle 5",
                "Wingle 7"],
        
        "Haval": ["Big Dog",
                  "Dargo",
                  "F7",
                  "F7x",
                  "H1",
                  "H2",
                  "H4",
                  "H5",
                  "H6",
                  "H7",
                  "H8",
                  "H9",
                  "Jolion",
                  "M6"],
        
        "Honda": ["Accord",
                  "Civic",
                  "CR-V",
                  "CR-Z",
                  "Element",
                  "Fit",
                  "HR-V",
                  "Insight",
                  "Odyssey",
                  "Passport",
                  "Pilot",
                  "Prelude",
                  "Ridgeline",
                  "S2000"],
        
        "Hongqi": ["E-HS9",
                   "H5",
                   "H7",
                   "H9",
                   "HS5",
                   "HS7",
                   "L5",
                   "LS7"],
        
        "Hummer": ["H1",
                   "H2",
                   "H3",
                   "EV Pickup",
                   "EV SUV"],
        
        "Hyundai": ["Accent",
                    "Azera",
                    "Elantra",
                    "Equus",
                    "Genesis",
                    "Ioniq",
                    "Kona",
                    "Palisade",
                    "Santa Fe",
                    "Sonata",
                    "Tucson",
                    "Veloster",
                    "Venue"],
        
        "Infiniti": ["EX",
                     "FX",
                     "G",
                     "I",
                     "J",
                     "M",
                     "Q30",
                     "Q40",
                     "Q50",
                     "Q60",
                     "Q70",
                     "QX30",
                     "QX50",
                     "QX60",
                     "QX70",
                     "QX80"],
        
        "Jac": ["iEV7",
                "J4",
                "J7",
                "S2",
                "S3",
                "S4",
                "S5",
                "S7",
                "T6",
                "T8",
                "Sunray"],
        
        "Jaecoo": ["J7",
                   "J8"],
        
        "Jaguar": ["E-Pace",
                   "F-Pace",
                   "F-Type",
                   "I-Pace",
                   "S-Type",
                   "X-Type",
                   "XE",
                   "XF",
                   "XJ",
                   "XK"],
        
        "Jeep": ["Cherokee",
                 "Commander",
                 "Compass",
                 "Grand Cherokee",
                 "Liberty",
                 "Patriot",
                 "Renegade",
                 "Wagoneer",
                 "Wrangler"],
        
        "Jetour": ["Dashing",
                   "Traveler",
                   "T1",
                   "T2",
                   "X70",
                   "X70 Plus",
                   "X90",
                   "X90 Plus"],
        
        "Kaiyi": ["E5",
                  "Kunlun",
                  "X3",
                  "X7"],
        
        "Kia": ["Cadenza",
                "Carnival",
                "Ceed",
                "Cerato",
                "Forte",
                "K5",
                "K900",
                "Niro",
                "Optima",
                "Picanto",
                "Rio",
                "Sedona",
                "Sorento",
                "Soul",
                "Sportage",
                "Stinger",
                "Telluride"],
        
        "Koenigsegg": ["Agera",
                       "CC8S",
                       "CCGT",
                       "CCX",
                       "Gemera",
                       "Jesko",
                       "One:1",
                       "Regera"],
        
        "Lada": ["2101",
                 "2103",
                 "2105",
                 "2106",
                 "2107",
                 "2110",
                 "2112",
                 "Granta",
                 "Kalina",
                 "Largus",
                 "Niva",
                 "Priora",
                 "Vesta",
                 "XRAY"],
        
        "Lamborghini": ["Aventador",
                        "Gallardo",
                        "Huracan",
                        "Murcielago",
                        "Reventon",
                        "Urus"],
        
        "Land Rover": ["Defender",
                       "Discovery",
                       "Discovery Sport",
                       "Evoque",
                       "Freelander",
                       "Range Rover",
                       "Range Rover Sport",
                       "Range Rover Velar"],
        
        "Leapmotor": ["C01",
                      "C10",
                      "C11",
                      "C16",
                      "S01",
                      "T03"],
        
        "Lexus": ["CT",
                  "ES",
                  "GS",
                  "GX",
                  "HS",
                  "IS",
                  "LC",
                  "LS",
                  "LX",
                  "NX",
                  "RC",
                  "RX",
                  "SC",
                  "UX"],
        
        "Li Auto": ["L6",
                    "L7",
                    "L8",
                    "L9",
                    "Mega",
                    "One"],
        
        "Lincoln": ["Aviator",
                    "Continental",
                    "Corsair",
                    "LS",
                    "MKC",
                    "MKS",
                    "MKT",
                    "MKX",
                    "MKZ",
                    "Navigator",
                    "Town Car"],
        
        "Lotus": ["Elan",
                  "Elise",
                  "Emeya",
                  "Emira",
                  "Eletre",
                  "Esprit",
                  "Evija",
                  "Europa",
                  "Exige"],
        
        "Lucid": ["Air",
                  "Gravity"],
        
        "Lynk & Co": ["01",
                      "02",
                      "03",
                      "05",
                      "06",
                      "08",
                      "09"],
        
        "Mahindra": ["Alturas G4",
                     "Bolero",
                     "Marazzo",
                     "Scorpio",
                     "Thar",
                     "Verito",
                     "XUV300",
                     "XUV400",
                     "XUV500",
                     "XUV700"],
        
        "Maserati": ["3200 GT",
                     "Ghibli",
                     "GranCabrio",
                     "GranTurismo",
                     "Grecale",
                     "Levante",
                     "MC20",
                     "Quattroporte"],
        
        "Maybach": ["57",
                    "62",
                    "GLS",
                    "S-Class",
                    "Pullman"],
        
        "Mazda": ["2",
                  "3",
                  "5",
                  "6",
                  "626",
                  "929",
                  "Atenza",
                  "Axela",
                  "B-Series",
                  "BT-50",
                  "CX-3",
                  "CX-5",
                  "CX-7",
                  "CX-9",
                  "CX-30",
                  "MPV",
                  "MX-5",
                  "Premacy",
                  "Protege",
                  "RX-7",
                  "RX-8",
                  "Tribute"],
        
        "McLaren": ["540C",
                    "570S",
                    "600LT",
                    "650S",
                    "675LT",
                    "720S",
                    "750S",
                    "765LT",
                    "Artura",
                    "Elva",
                    "F1",
                    "GT",
                    "MP4-12C",
                    "P1",
                    "Senna",
                    "Speedtail"],
        
        "Mercedes-Benz": ["A-Class",
                          "B-Class",
                          "C-Class",
                          "CL-Class",
                          "CLA-Class",
                          "CLK-Class",
                          "CLS-Class",
                          "E-Class",
                          "G-Class",
                          "GL-Class",
                          "GLA-Class",
                          "GLB-Class",
                          "GLC-Class",
                          "GLE-Class",
                          "GLK-Class",
                          "GLS-Class",
                          "M-Class",
                          "ML-Class",
                          "R-Class",
                          "S-Class",
                          "SL-Class",
                          "SLK-Class",
                          "SLR McLaren",
                          "SLS AMG",
                          "V-Class",
                          "Viano",
                          "Vito"],
        
        "MG": ["3",
               "5",
               "6",
               "7",
               "Cyberster",
               "GT",
               "HS",
               "MG One",
               "RX5",
               "RX8",
               "ZS"],
        
        "Mini": ["Clubman",
                 "Countryman",
                 "Coupe",
                 "Hatch",
                 "Paceman",
                 "Roadster"],
        
        "Mitsubishi": ["3000GT",
                       "ASX",
                       "Challenger",
                       "Colt",
                       "Eclipse",
                       "Eclipse Cross",
                       "Endeavor",
                       "Evolution",
                       "Galant",
                       "Grandis",
                       "i-MiEV",
                       "Lancer",
                       "Mirage",
                       "Montero",
                       "Outlander",
                       "Pajero",
                       "Space Star"],
        
        "Nio": ["EC6",
                "EC7",
                "EL6",
                "EL7",
                "ES6",
                "ES7",
                "ES8",
                "ET5",
                "ET7"],
        
        "Nissan": ["350Z",
                   "370Z",
                   "Altima",
                   "Armada",
                   "Cube",
                   "Frontier",
                   "GT-R",
                   "Juke",
                   "Leaf",
                   "Maxima",
                   "Murano",
                   "Navara",
                   "Note",
                   "NV200",
                   "Pathfinder",
                   "Patrol",
                   "Qashqai",
                   "Quest",
                   "Rogue",
                   "Sentra",
                   "Sunny",
                   "Titan",
                   "Versa",
                   "X-Trail",
                   "Xterra"],
        
        "Omoda": ["3",
                  "5"],
        
        "Opel": ["Adam",
                 "Agila",
                 "Antara",
                 "Astra",
                 "Calibra",
                 "Corsa",
                 "Crossland",
                 "Frontera",
                 "Grandland",
                 "Insignia",
                 "Kadett",
                 "Manta",
                 "Meriva",
                 "Mokka",
                 "Omega",
                 "Rekord",
                 "Signum",
                 "Vectra",
                 "Zafira"],
        
        "Pagani": ["Huayra",
                   "Utopia",
                   "Zonda"],
        
        "Peugeot": ["106",
                    "107",
                    "108",
                    "205",
                    "206",
                    "207",
                    "208",
                    "301",
                    "306",
                    "307",
                    "308",
                    "405",
                    "406",
                    "407",
                    "408",
                    "508",
                    "2008",
                    "3008",
                    "4007",
                    "4008",
                    "5008",
                    "Expert",
                    "Partner",
                    "Rifter"],
        
        "Polaris": ["General",
                    "Ranger",
                    "RZR",
                    "Scrambler",
                    "Sportsman"],
        
        "Pontiac": ["Aztek",
                    "Bonneville",
                    "Fiero",
                    "Firebird",
                    "G3",
                    "G5",
                    "G6",
                    "G8",
                    "Grand Am",
                    "Grand Prix",
                    "GTO",
                    "Montana",
                    "Solstice",
                    "Sunfire",
                    "Torrent",
                    "Trans Sport",
                    "Vibe"],
        
        "Porsche": ["911",
                    "918 Spyder",
                    "Boxster",
                    "Cayenne",
                    "Cayman",
                    "Macan",
                    "Panamera",
                    "Taycan"],
        
        "Ram": ["1500",
                "2500",
                "3500",
                "4500",
                "5500",
                "Dakota",
                "ProMaster",
                "ProMaster City",
                "TRX"],
        
        "Renault": ["Arkana",
                    "Captur",
                    "Clio",
                    "Duster",
                    "Espace",
                    "Fluence",
                    "Kadjar",
                    "Kangoo",
                    "Kaptur",
                    "Koleos",
                    "Laguna",
                    "Logan",
                    "Megane",
                    "Sandero",
                    "Symbol",
                    "Talisman",
                    "Trafic",
                    "Twingo",
                    "Zoe"],
        
        "Rivian": ["R1S",
                   "R1T",
                   "EDV 500",
                   "EDV 700"],
        
        "Rolls-Royce": ["Cullinan",
                        "Dawn",
                        "Ghost",
                        "Phantom",
                        "Silver Cloud",
                        "Silver Shadow",
                        "Silver Spirit",
                        "Silver Spur",
                        "Spectre",
                        "Wraith"],
        
        "Rox": ["01"],
        
        "Skoda": ["Citigo",
                  "Fabia",
                  "Kamiq",
                  "Karoq",
                  "Kodiaq",
                  "Octavia",
                  "Rapid",
                  "Roomster",
                  "Scala",
                  "Superb",
                  "Yeti"],
        
        "Smart": ["ForTwo",
                  "ForFour",
                  "#1",
                  "#3",
                  "Roadster"],
        
        "Soueast": ["A5",
                    "DX3",
                    "DX5",
                    "DX7"],
        
        "SsangYong": ["Actyon",
                      "Korando",
                      "Kyron",
                      "Musso",
                      "Rexton",
                      "Tivoli",
                      "Torres"],
        
        "Subaru": ["Ascent",
                   "BRZ",
                   "Crosstrek",
                   "Forester",
                   "Impreza",
                   "Legacy",
                   "Outback",
                   "SVX",
                   "Tribeca",
                   "WRX"],
        
        "Suzuki": ["Alto",
                   "Baleno",
                   "Celerio",
                   "Ertiga",
                   "Grand Vitara",
                   "Ignis",
                   "Jimny",
                   "Kizashi",
                   "Liana",
                   "Samurai",
                   "S-Presso",
                   "Swift",
                   "SX4",
                   "Vitara",
                   "Wagon R",
                   "XL7"],
        
        "Tata": ["Altroz",
                 "Aria",
                 "Harrier",
                 "Hexa",
                 "Indica",
                 "Indigo",
                 "Nano",
                 "Nexon",
                 "Punch",
                 "Safari",
                 "Sierra",
                 "Tiago",
                 "Tigor"],
        
        "Tesla": ["Model 3",
                  "Model S",
                  "Model X",
                  "Model Y",
                  "Roadster"],
        
        "Toyota": ["4Runner",
                   "86",
                   "Avalon",
                   "Avensis",
                   "C-HR",
                   "Camry",
                   "Celica",
                   "Corolla",
                   "Crown",
                   "FJ Cruiser",
                   "Highlander",
                   "Land Cruiser",
                   "Matrix",
                   "Prius",
                   "RAV4",
                   "Sequoia",
                   "Sienna",
                   "Supra",
                   "Tacoma",
                   "Tundra",
                   "Venza",
                   "Vios",
                   "Yaris"],
        
        "UAZ": ["469",
                "Bukhanka",
                "Hunter",
                "Patriot",
                "Pickup",
                "Profi"],
        
        "Volkswagen": ["Arteon",
                       "Atlas",
                       "Beetle",
                       "CC",
                       "Eos",
                       "Golf",
                       "Jetta",
                       "Passat",
                       "Polo",
                       "Scirocco",
                       "Tiguan",
                       "Touareg",
                       "Touran"],
        
        "Volvo": ["C30",
                  "C70",
                  "S40",
                  "S60",
                  "S80",
                  "S90",
                  "V40",
                  "V50",
                  "V60",
                  "V70",
                  "V90",
                  "XC40",
                  "XC60",
                  "XC70",
                  "XC90"],
        
        "Voyah": ["Dreamer",
                  "Free",
                  "Passion"],
        
        "Xpeng": ["G3",
                  "G6",
                  "G9",
                  "P5",
                  "P7",
                  "X9"],
        
        "Zeekr": ["001",
                  "007",
                  "009",
                  "X"]

    ]
}
